[2024-05-06 07:31:36,278] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.local_to_gcs_task scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2024-05-06 07:31:36,290] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.local_to_gcs_task scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2024-05-06 07:31:36,291] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 07:31:36,291] {taskinstance.py:1239} INFO - Starting attempt 4 of 6
[2024-05-06 07:31:36,292] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 07:31:36,305] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-08-02 06:00:00+00:00
[2024-05-06 07:31:36,311] {standard_task_runner.py:52} INFO - Started process 2823 to run task
[2024-05-06 07:31:36,317] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'local_to_gcs_task', 'scheduled__2019-08-02T06:00:00+00:00', '--job-id', '4490', '--raw', '--subdir', 'DAGS_FOLDER/data_ingstion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmpcs7709ev', '--error-file', '/tmp/tmporhvmrbz']
[2024-05-06 07:31:36,323] {standard_task_runner.py:77} INFO - Job 4490: Subtask local_to_gcs_task
[2024-05-06 07:31:36,402] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.local_to_gcs_task scheduled__2019-08-02T06:00:00+00:00 [running]> on host 1aa5194a14e3
[2024-05-06 07:31:36,454] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-06 07:31:36,489] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-02T06:00:00+00:00
[2024-05-06 07:31:49,985] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/operators/python.py:174: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  return_value = self.execute_callable()

[2024-05-06 07:32:02,990] {python.py:175} INFO - Done. Returned value was: None
[2024-05-06 07:32:03,018] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_yt, task_id=local_to_gcs_task, execution_date=20190802T060000, start_date=20240506T073136, end_date=20240506T073203
[2024-05-06 07:32:03,095] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-06 07:32:03,146] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-06 09:31:34,442] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.local_to_gcs_task scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2024-05-06 09:31:34,566] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.local_to_gcs_task scheduled__2019-08-02T06:00:00+00:00 [queued]>
[2024-05-06 09:31:34,573] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 09:31:34,573] {taskinstance.py:1239} INFO - Starting attempt 4 of 6
[2024-05-06 09:31:34,581] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 09:31:34,665] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-08-02 06:00:00+00:00
[2024-05-06 09:31:34,716] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'local_to_gcs_task', 'scheduled__2019-08-02T06:00:00+00:00', '--job-id', '4638', '--raw', '--subdir', 'DAGS_FOLDER/data_ingstion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmpbxjqrq7b', '--error-file', '/tmp/tmp0dg05p93']
[2024-05-06 09:31:34,769] {standard_task_runner.py:77} INFO - Job 4638: Subtask local_to_gcs_task
[2024-05-06 09:31:34,703] {standard_task_runner.py:52} INFO - Started process 846 to run task
[2024-05-06 09:31:35,186] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.local_to_gcs_task scheduled__2019-08-02T06:00:00+00:00 [running]> on host 4d4efceb404e
[2024-05-06 09:31:35,469] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-06 09:31:35,594] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-08-02T06:00:00+00:00
