[2024-03-29 08:27:41,625] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-29 08:27:41,678] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-29 08:27:41,678] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-29 08:27:41,678] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-29 08:27:41,678] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-29 08:27:41,852] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-03-02 06:00:00+00:00
[2024-03-29 08:27:42,031] {standard_task_runner.py:52} INFO - Started process 1643 to run task
[2024-03-29 08:27:42,071] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-03-02T06:00:00+00:00', '--job-id', '1791', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpb76c55n1', '--error-file', '/tmp/tmpxqnatczt']
[2024-03-29 08:27:42,128] {standard_task_runner.py:77} INFO - Job 1791: Subtask local_to_gcs_task
[2024-03-29 08:27:43,029] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [running]> on host b5e5a5778b83
[2024-03-29 08:27:43,607] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-29 08:27:44,309] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T06:00:00+00:00
[2024-03-29 08:27:45,980] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-03.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_03.parquet.
[2024-03-29 08:27:45,980] {python.py:175} INFO - Done. Returned value was: None
[2024-03-29 08:27:46,042] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20230302T060000, start_date=20240329T082741, end_date=20240329T082746
[2024-03-29 08:27:46,161] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-29 08:27:46,700] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30 03:53:42,321] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 03:53:42,603] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 03:53:42,603] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 03:53:42,603] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 03:53:42,603] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 03:53:43,624] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-03-02 06:00:00+00:00
[2024-03-30 03:53:43,666] {standard_task_runner.py:52} INFO - Started process 2186 to run task
[2024-03-30 03:53:43,677] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-03-02T06:00:00+00:00', '--job-id', '2004', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpaj_5cfe2', '--error-file', '/tmp/tmpl0lwokfv']
[2024-03-30 03:53:43,697] {standard_task_runner.py:77} INFO - Job 2004: Subtask local_to_gcs_task
[2024-03-30 03:53:44,700] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 03:53:45,228] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 03:53:45,409] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T06:00:00+00:00
[2024-03-30 03:53:47,659] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-03.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_03.parquet.
[2024-03-30 03:53:47,660] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 03:53:47,938] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20230302T060000, start_date=20240330T035342, end_date=20240330T035347
[2024-03-30 03:53:48,194] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 03:53:48,437] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 04:19:14,219] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 04:19:14,269] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 04:19:14,270] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:19:14,271] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 04:19:14,271] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:19:14,293] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-03-02 06:00:00+00:00
[2024-03-30 04:19:14,302] {standard_task_runner.py:52} INFO - Started process 3830 to run task
[2024-03-30 04:19:14,344] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-03-02T06:00:00+00:00', '--job-id', '2150', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpy3phqlfu', '--error-file', '/tmp/tmpuxnsn55f']
[2024-03-30 04:19:14,351] {standard_task_runner.py:77} INFO - Job 2150: Subtask local_to_gcs_task
[2024-03-30 04:19:14,571] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 04:19:14,668] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 04:19:14,720] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T06:00:00+00:00
[2024-03-30 04:19:15,187] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-03.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_03.parquet.
[2024-03-30 04:19:15,187] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 04:19:15,202] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20230302T060000, start_date=20240330T041914, end_date=20240330T041915
[2024-03-30 04:19:15,243] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 04:19:15,285] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 04:25:48,706] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 04:25:48,783] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 04:25:48,783] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:25:48,784] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 04:25:48,785] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:25:49,178] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-03-02 06:00:00+00:00
[2024-03-30 04:25:49,187] {standard_task_runner.py:52} INFO - Started process 4470 to run task
[2024-03-30 04:25:49,223] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-03-02T06:00:00+00:00', '--job-id', '2232', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmptz0er90r', '--error-file', '/tmp/tmpspr6o7cw']
[2024-03-30 04:25:49,241] {standard_task_runner.py:77} INFO - Job 2232: Subtask local_to_gcs_task
[2024-03-30 04:25:49,799] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 04:25:50,247] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 04:25:50,355] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T06:00:00+00:00
[2024-03-30 04:25:51,429] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-03.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_03.parquet.
[2024-03-30 04:25:51,429] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 04:25:51,551] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20230302T060000, start_date=20240330T042548, end_date=20240330T042551
[2024-03-30 04:25:51,635] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 04:25:51,827] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 04:45:04,371] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 04:45:04,424] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 04:45:04,424] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:45:04,425] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 04:45:04,425] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:45:04,480] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-03-02 06:00:00+00:00
[2024-03-30 04:45:04,504] {standard_task_runner.py:52} INFO - Started process 5834 to run task
[2024-03-30 04:45:04,541] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-03-02T06:00:00+00:00', '--job-id', '2369', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpg_t96ftu', '--error-file', '/tmp/tmpq908ople']
[2024-03-30 04:45:04,563] {standard_task_runner.py:77} INFO - Job 2369: Subtask local_to_gcs_task
[2024-03-30 04:45:04,852] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 04:45:05,075] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 04:45:05,215] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T06:00:00+00:00
[2024-03-30 04:45:06,200] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-03.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_03.parquet.
[2024-03-30 04:45:06,200] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 04:45:06,642] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20230302T060000, start_date=20240330T044504, end_date=20240330T044506
[2024-03-30 04:45:07,039] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 04:45:07,575] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 05:00:23,762] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 05:00:23,857] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 05:00:23,857] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 05:00:23,857] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 05:00:23,857] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 05:00:23,967] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-03-02 06:00:00+00:00
[2024-03-30 05:00:23,988] {standard_task_runner.py:52} INFO - Started process 6896 to run task
[2024-03-30 05:00:24,048] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-03-02T06:00:00+00:00', '--job-id', '2472', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp2qqxm675', '--error-file', '/tmp/tmpy8yz3px0']
[2024-03-30 05:00:24,069] {standard_task_runner.py:77} INFO - Job 2472: Subtask local_to_gcs_task
[2024-03-30 05:00:24,732] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 05:00:25,025] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 05:00:25,107] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T06:00:00+00:00
[2024-03-30 05:00:25,967] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-03.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_03.parquet.
[2024-03-30 05:00:25,968] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 05:00:26,028] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20230302T060000, start_date=20240330T050023, end_date=20240330T050026
[2024-03-30 05:00:26,672] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 05:00:27,079] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 09:03:01,783] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 09:03:01,885] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 09:03:01,886] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 09:03:01,890] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 09:03:01,892] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 09:03:01,987] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-03-02 06:00:00+00:00
[2024-03-30 09:03:02,019] {standard_task_runner.py:52} INFO - Started process 18445 to run task
[2024-03-30 09:03:02,094] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-03-02T06:00:00+00:00', '--job-id', '2588', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp2zxs7rp8', '--error-file', '/tmp/tmpuk2p7j1u']
[2024-03-30 09:03:02,114] {standard_task_runner.py:77} INFO - Job 2588: Subtask local_to_gcs_task
[2024-03-30 09:03:02,625] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 09:03:03,236] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 09:03:03,497] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T06:00:00+00:00
[2024-03-30 09:03:05,214] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2023-03.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2023_03.parquet.
[2024-03-30 09:03:05,215] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 09:03:05,257] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20230302T060000, start_date=20240330T090301, end_date=20240330T090305
[2024-03-30 09:03:05,388] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 09:03:05,525] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 11:57:29,133] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 11:57:29,229] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-03-30 11:57:29,229] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 11:57:29,229] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 11:57:29,229] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 11:57:29,507] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-03-02 06:00:00+00:00
[2024-03-30 11:57:29,561] {standard_task_runner.py:52} INFO - Started process 28609 to run task
[2024-03-30 11:57:29,600] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-03-02T06:00:00+00:00', '--job-id', '2905', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpb70ir6lw', '--error-file', '/tmp/tmp_q_s1103']
[2024-03-30 11:57:29,613] {standard_task_runner.py:77} INFO - Job 2905: Subtask local_to_gcs_task
[2024-03-30 11:57:30,035] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 11:57:30,144] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 11:57:30,367] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T06:00:00+00:00
[2024-03-30 11:57:45,303] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 68, in upload_to_gcs
    df.to_parquet(clean_file_name, index=False)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2372, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 276, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 101, in write
    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
  File "pyarrow/table.pxi", line 1561, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 607, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 581, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 575, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 302, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column store_and_fwd_flag with type object')
[2024-03-30 11:57:45,484] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20230302T060000, start_date=20240330T115729, end_date=20240330T115745
[2024-03-30 11:57:45,620] {standard_task_runner.py:92} ERROR - Failed to execute job 2905 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 68, in upload_to_gcs
    df.to_parquet(clean_file_name, index=False)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2372, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 276, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 101, in write
    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
  File "pyarrow/table.pxi", line 1561, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 607, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 581, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 575, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 302, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column store_and_fwd_flag with type object')
[2024-03-30 11:57:45,883] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-30 11:57:46,387] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30 03:02:07,561] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-04-30 03:02:07,651] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-04-30 03:02:07,651] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 03:02:07,652] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-04-30 03:02:07,652] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 03:02:07,723] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-03-02 06:00:00+00:00
[2024-04-30 03:02:07,769] {standard_task_runner.py:52} INFO - Started process 957 to run task
[2024-04-30 03:02:07,808] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-03-02T06:00:00+00:00', '--job-id', '3195', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp0k8gxsv5', '--error-file', '/tmp/tmp_4yaqxl9']
[2024-04-30 03:02:07,868] {standard_task_runner.py:77} INFO - Job 3195: Subtask local_to_gcs_task
[2024-04-30 03:02:08,349] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [running]> on host 02dc49e0e362
[2024-04-30 03:02:08,652] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-30 03:02:08,776] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T06:00:00+00:00
[2024-04-30 03:02:10,728] {python.py:175} INFO - Done. Returned value was: None
[2024-04-30 03:02:10,757] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20230302T060000, start_date=20240430T030207, end_date=20240430T030210
[2024-04-30 03:02:10,895] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-04-30 03:02:11,103] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-30 04:34:44,964] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-04-30 04:34:45,033] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [queued]>
[2024-04-30 04:34:45,034] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 04:34:45,035] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-04-30 04:34:45,035] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 04:34:45,093] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2023-03-02 06:00:00+00:00
[2024-04-30 04:34:45,140] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2023-03-02T06:00:00+00:00', '--job-id', '3302', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpregs2hyg', '--error-file', '/tmp/tmpaek1f0m4']
[2024-04-30 04:34:45,148] {standard_task_runner.py:77} INFO - Job 3302: Subtask local_to_gcs_task
[2024-04-30 04:34:45,132] {standard_task_runner.py:52} INFO - Started process 5720 to run task
[2024-04-30 04:34:45,337] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2023-03-02T06:00:00+00:00 [running]> on host 02dc49e0e362
[2024-04-30 04:34:45,524] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-30 04:34:45,643] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T06:00:00+00:00
[2024-04-30 04:34:56,975] {python.py:175} INFO - Done. Returned value was: None
[2024-04-30 04:34:57,000] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20230302T060000, start_date=20240430T043444, end_date=20240430T043457
[2024-04-30 04:34:57,057] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-04-30 04:34:57,118] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
