[2024-03-26 15:16:45,457] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-26 15:16:45,469] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-26 15:16:45,470] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 15:16:45,470] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 15:16:45,470] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 15:16:45,486] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2024-02-02 06:00:00+00:00
[2024-03-26 15:16:45,493] {standard_task_runner.py:52} INFO - Started process 266 to run task
[2024-03-26 15:16:45,499] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2024-02-02T06:00:00+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp4m8jx92h', '--error-file', '/tmp/tmp1z1ggngk']
[2024-03-26 15:16:45,500] {standard_task_runner.py:77} INFO - Job 260: Subtask download_dataset_task
[2024-03-26 15:16:45,578] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [running]> on host 153a478eba08
[2024-03-26 15:16:45,620] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 15:16:45,647] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-02T06:00:00+00:00
[2024-03-26 15:16:45,648] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 15:16:45,649] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL <***.models.param.DagParam object at 0x7f776545a208> > /opt/***/raw_data/yellowtaxi _tripdata_2024-02.csv']
[2024-03-26 15:16:45,661] {subprocess.py:85} INFO - Output:
[2024-03-26 15:16:45,663] {subprocess.py:89} INFO - bash: -c: line 0: syntax error near unexpected token `>'
[2024-03-26 15:16:45,664] {subprocess.py:89} INFO - bash: -c: line 0: `curl -sSL <***.models.param.DagParam object at 0x7f776545a208> > /opt/***/raw_data/yellowtaxi _tripdata_2024-02.csv'
[2024-03-26 15:16:45,664] {subprocess.py:93} INFO - Command exited with return code 1
[2024-03-26 15:16:45,679] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-26 15:16:45,687] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20240202T060000, start_date=20240326T151645, end_date=20240326T151645
[2024-03-26 15:16:45,700] {standard_task_runner.py:92} ERROR - Failed to execute job 260 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-26 15:16:45,714] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 15:16:45,759] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:34:34,107] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-26 17:34:34,165] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-26 17:34:34,166] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:34:34,166] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:34:34,166] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:34:34,244] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2024-02-02 06:00:00+00:00
[2024-03-26 17:34:34,267] {standard_task_runner.py:52} INFO - Started process 3002 to run task
[2024-03-26 17:34:34,310] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2024-02-02T06:00:00+00:00', '--job-id', '451', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpmcsy1z26', '--error-file', '/tmp/tmpwtxdl3ys']
[2024-03-26 17:34:34,312] {standard_task_runner.py:77} INFO - Job 451: Subtask download_dataset_task
[2024-03-26 17:34:34,727] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [running]> on host d71984e59113
[2024-03-26 17:34:34,945] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:34:35,033] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-02T06:00:00+00:00
[2024-03-26 17:34:35,035] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:34:35,038] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-02.parquet > /opt/***/yellowtaxi_tripdata_2024-02.parquet']
[2024-03-26 17:34:35,080] {subprocess.py:85} INFO - Output:
[2024-03-26 17:34:36,363] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:34:36,730] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20240202T060000, start_date=20240326T173434, end_date=20240326T173436
[2024-03-26 17:34:37,020] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:34:37,739] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:49:12,785] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-26 17:49:12,798] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-26 17:49:12,798] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:49:12,798] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:49:12,798] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:49:12,809] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2024-02-02 06:00:00+00:00
[2024-03-26 17:49:12,817] {standard_task_runner.py:52} INFO - Started process 407 to run task
[2024-03-26 17:49:12,823] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2024-02-02T06:00:00+00:00', '--job-id', '532', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpmicu7ecx', '--error-file', '/tmp/tmpg__c_sob']
[2024-03-26 17:49:12,823] {standard_task_runner.py:77} INFO - Job 532: Subtask download_dataset_task
[2024-03-26 17:49:12,888] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:49:12,930] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:49:12,951] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-02T06:00:00+00:00
[2024-03-26 17:49:12,952] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:49:12,953] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-02.parquet > /opt/***/yellowtaxi_tripdata_2024-02.parquet']
[2024-03-26 17:49:12,965] {subprocess.py:85} INFO - Output:
[2024-03-26 17:49:14,140] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:49:14,174] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20240202T060000, start_date=20240326T174912, end_date=20240326T174914
[2024-03-26 17:49:14,202] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:49:14,241] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:52:43,413] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-26 17:52:43,432] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-26 17:52:43,432] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:52:43,432] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:52:43,432] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:52:43,453] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2024-02-02 06:00:00+00:00
[2024-03-26 17:52:43,462] {standard_task_runner.py:52} INFO - Started process 825 to run task
[2024-03-26 17:52:43,467] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2024-02-02T06:00:00+00:00', '--job-id', '607', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpakf0vrpx', '--error-file', '/tmp/tmpww5z0ith']
[2024-03-26 17:52:43,468] {standard_task_runner.py:77} INFO - Job 607: Subtask download_dataset_task
[2024-03-26 17:52:43,538] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:52:43,586] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:52:43,611] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-02T06:00:00+00:00
[2024-03-26 17:52:43,612] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:52:43,613] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-02.parquet > /opt/***/yellowtaxi_tripdata_2024-02.parquet']
[2024-03-26 17:52:43,628] {subprocess.py:85} INFO - Output:
[2024-03-26 17:52:44,789] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:52:44,827] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20240202T060000, start_date=20240326T175243, end_date=20240326T175244
[2024-03-26 17:52:44,885] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:52:44,931] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-26 18:22:37,412] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-26 18:22:37,428] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-26 18:22:37,428] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:22:37,428] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 18:22:37,428] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:22:37,442] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2024-02-02 06:00:00+00:00
[2024-03-26 18:22:37,449] {standard_task_runner.py:52} INFO - Started process 400 to run task
[2024-03-26 18:22:37,454] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2024-02-02T06:00:00+00:00', '--job-id', '718', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpkgnm7ecl', '--error-file', '/tmp/tmpk55ab1fn']
[2024-03-26 18:22:37,454] {standard_task_runner.py:77} INFO - Job 718: Subtask download_dataset_task
[2024-03-26 18:22:37,518] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 18:22:37,560] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 18:22:37,583] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-02T06:00:00+00:00
[2024-03-26 18:22:37,584] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 18:22:37,585] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-02.parquet > /opt/***/yellowtaxi_tripdata_2024-02.parquet']
[2024-03-26 18:22:37,599] {subprocess.py:85} INFO - Output:
[2024-03-26 18:22:38,773] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 18:22:38,805] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20240202T060000, start_date=20240326T182237, end_date=20240326T182238
[2024-03-26 18:22:38,832] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 18:22:38,879] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-27 03:48:31,225] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-27 03:48:31,235] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [queued]>
[2024-03-27 03:48:31,235] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 03:48:31,235] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-27 03:48:31,235] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 03:48:31,243] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2024-02-02 06:00:00+00:00
[2024-03-27 03:48:31,247] {standard_task_runner.py:52} INFO - Started process 411 to run task
[2024-03-27 03:48:31,249] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2024-02-02T06:00:00+00:00', '--job-id', '793', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp9eot3zdq', '--error-file', '/tmp/tmpzgfhrsqj']
[2024-03-27 03:48:31,249] {standard_task_runner.py:77} INFO - Job 793: Subtask download_dataset_task
[2024-03-27 03:48:31,289] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2024-02-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-27 03:48:31,315] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-27 03:48:31,328] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2024-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-02T06:00:00+00:00
[2024-03-27 03:48:31,329] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-27 03:48:31,336] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-02.parquet > /opt/***/yellowtaxi_tripdata_2024-02.parquet']
[2024-03-27 03:48:31,344] {subprocess.py:85} INFO - Output:
[2024-03-27 03:48:32,508] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-27 03:48:32,527] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20240202T060000, start_date=20240327T034831, end_date=20240327T034832
[2024-03-27 03:48:32,545] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-27 03:48:32,570] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
