[2024-05-12 12:41:47,460] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_gt.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2024-05-12 12:41:47,578] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_gt.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2024-05-12 12:41:47,581] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-12 12:41:47,581] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2024-05-12 12:41:47,582] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-12 12:41:47,665] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-02 06:00:00+00:00
[2024-05-12 12:41:47,771] {standard_task_runner.py:52} INFO - Started process 641 to run task
[2024-05-12 12:41:47,841] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_gt', 'local_to_gcs_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '4833', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_gt_dag .py', '--cfg-path', '/tmp/tmp5l7p51iv', '--error-file', '/tmp/tmp9ux020n3']
[2024-05-12 12:41:47,870] {standard_task_runner.py:77} INFO - Job 4833: Subtask local_to_gcs_task
[2024-05-12 12:41:48,135] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_gt.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host 31858b145400
[2024-05-12 12:41:48,423] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-12 12:41:48,624] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_gt
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2024-05-12 12:42:05,467] {python.py:175} INFO - Done. Returned value was: None
[2024-05-12 12:42:05,484] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_gt, task_id=local_to_gcs_task, execution_date=20190302T060000, start_date=20240512T124147, end_date=20240512T124205
[2024-05-12 12:42:05,672] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-12 12:42:05,812] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-18 11:09:28,513] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_gt.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2024-05-18 11:09:28,760] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_gt.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2024-05-18 11:09:28,760] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-18 11:09:28,760] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2024-05-18 11:09:28,760] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-18 11:09:28,847] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-02 06:00:00+00:00
[2024-05-18 11:09:28,932] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_gt', 'local_to_gcs_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '4929', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_gt_dag .py', '--cfg-path', '/tmp/tmp4giwl_zr', '--error-file', '/tmp/tmphqunamo_']
[2024-05-18 11:09:28,951] {standard_task_runner.py:77} INFO - Job 4929: Subtask local_to_gcs_task
[2024-05-18 11:09:28,927] {standard_task_runner.py:52} INFO - Started process 1176 to run task
[2024-05-18 11:09:29,092] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_gt.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host 45b18388e83d
[2024-05-18 11:09:29,211] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-18 11:09:29,419] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_gt
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2024-05-18 11:09:47,871] {python.py:175} INFO - Done. Returned value was: None
[2024-05-18 11:09:47,929] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_gt, task_id=local_to_gcs_task, execution_date=20190302T060000, start_date=20240518T110928, end_date=20240518T110947
[2024-05-18 11:09:48,196] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-18 11:09:48,375] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
