[2024-03-29 08:27:37,365] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-29 08:27:37,500] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-29 08:27:37,501] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-29 08:27:37,511] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-29 08:27:37,517] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-29 08:27:37,681] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-02 06:00:00+00:00
[2024-03-29 08:27:37,742] {standard_task_runner.py:52} INFO - Started process 1625 to run task
[2024-03-29 08:27:37,845] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2022-12-02T06:00:00+00:00', '--job-id', '1790', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpjnpb6r62', '--error-file', '/tmp/tmppx2sbrey']
[2024-03-29 08:27:37,968] {standard_task_runner.py:77} INFO - Job 1790: Subtask local_to_gcs_task
[2024-03-29 08:27:38,435] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [running]> on host b5e5a5778b83
[2024-03-29 08:27:38,955] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-29 08:27:39,225] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T06:00:00+00:00
[2024-03-29 08:27:41,367] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2022-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2022_12.parquet.
[2024-03-29 08:27:41,418] {python.py:175} INFO - Done. Returned value was: None
[2024-03-29 08:27:41,454] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20221202T060000, start_date=20240329T082737, end_date=20240329T082741
[2024-03-29 08:27:41,702] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-29 08:27:41,991] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 03:53:37,178] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 03:53:37,243] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 03:53:37,244] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 03:53:37,244] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 03:53:37,245] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 03:53:37,299] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-02 06:00:00+00:00
[2024-03-30 03:53:37,322] {standard_task_runner.py:52} INFO - Started process 2168 to run task
[2024-03-30 03:53:37,413] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2022-12-02T06:00:00+00:00', '--job-id', '2000', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp3evuqmmf', '--error-file', '/tmp/tmp9higqtwj']
[2024-03-30 03:53:37,473] {standard_task_runner.py:77} INFO - Job 2000: Subtask local_to_gcs_task
[2024-03-30 03:53:37,962] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 03:53:38,402] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 03:53:38,547] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T06:00:00+00:00
[2024-03-30 03:53:39,568] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2022-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2022_12.parquet.
[2024-03-30 03:53:39,568] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 03:53:39,941] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20221202T060000, start_date=20240330T035337, end_date=20240330T035339
[2024-03-30 03:53:40,116] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 03:53:40,219] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 04:19:11,863] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 04:19:11,924] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 04:19:11,924] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:19:11,924] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 04:19:11,924] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:19:11,982] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-02 06:00:00+00:00
[2024-03-30 04:19:12,027] {standard_task_runner.py:52} INFO - Started process 3820 to run task
[2024-03-30 04:19:12,068] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2022-12-02T06:00:00+00:00', '--job-id', '2145', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpd47zy6rt', '--error-file', '/tmp/tmpfnz300dh']
[2024-03-30 04:19:12,076] {standard_task_runner.py:77} INFO - Job 2145: Subtask local_to_gcs_task
[2024-03-30 04:19:12,222] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 04:19:12,392] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 04:19:12,479] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T06:00:00+00:00
[2024-03-30 04:19:13,214] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2022-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2022_12.parquet.
[2024-03-30 04:19:13,215] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 04:19:13,244] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20221202T060000, start_date=20240330T041911, end_date=20240330T041913
[2024-03-30 04:19:13,318] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 04:19:13,440] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 04:25:47,404] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 04:25:47,602] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 04:25:47,603] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:25:47,603] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 04:25:47,603] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:25:47,702] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-02 06:00:00+00:00
[2024-03-30 04:25:47,714] {standard_task_runner.py:52} INFO - Started process 4459 to run task
[2024-03-30 04:25:47,814] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2022-12-02T06:00:00+00:00', '--job-id', '2225', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp1uuua2me', '--error-file', '/tmp/tmptgn3y2cr']
[2024-03-30 04:25:47,863] {standard_task_runner.py:77} INFO - Job 2225: Subtask local_to_gcs_task
[2024-03-30 04:25:48,819] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 04:25:49,291] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 04:25:49,391] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T06:00:00+00:00
[2024-03-30 04:25:50,975] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2022-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2022_12.parquet.
[2024-03-30 04:25:50,975] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 04:25:51,014] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20221202T060000, start_date=20240330T042547, end_date=20240330T042551
[2024-03-30 04:25:51,150] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 04:25:51,599] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30 04:45:00,136] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 04:45:00,175] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 04:45:00,175] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:45:00,176] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 04:45:00,176] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 04:45:00,227] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-02 06:00:00+00:00
[2024-03-30 04:45:00,287] {standard_task_runner.py:52} INFO - Started process 5815 to run task
[2024-03-30 04:45:00,348] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2022-12-02T06:00:00+00:00', '--job-id', '2365', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpgelj1fp6', '--error-file', '/tmp/tmp409zoodg']
[2024-03-30 04:45:00,381] {standard_task_runner.py:77} INFO - Job 2365: Subtask local_to_gcs_task
[2024-03-30 04:45:00,601] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 04:45:00,828] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 04:45:01,026] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T06:00:00+00:00
[2024-03-30 04:45:01,948] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2022-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2022_12.parquet.
[2024-03-30 04:45:01,948] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 04:45:01,989] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20221202T060000, start_date=20240330T044500, end_date=20240330T044501
[2024-03-30 04:45:02,251] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 04:45:02,333] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 05:00:21,398] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 05:00:21,459] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 05:00:21,466] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 05:00:21,467] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 05:00:21,468] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 05:00:21,552] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-02 06:00:00+00:00
[2024-03-30 05:00:21,606] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2022-12-02T06:00:00+00:00', '--job-id', '2467', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpzcvd73z6', '--error-file', '/tmp/tmpizr6w5h3']
[2024-03-30 05:00:21,577] {standard_task_runner.py:52} INFO - Started process 6884 to run task
[2024-03-30 05:00:21,620] {standard_task_runner.py:77} INFO - Job 2467: Subtask local_to_gcs_task
[2024-03-30 05:00:21,867] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 05:00:22,132] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 05:00:22,223] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T06:00:00+00:00
[2024-03-30 05:00:23,549] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2022-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2022_12.parquet.
[2024-03-30 05:00:23,550] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 05:00:23,581] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20221202T060000, start_date=20240330T050021, end_date=20240330T050023
[2024-03-30 05:00:23,744] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 05:00:23,882] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-30 09:02:53,210] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 09:02:53,669] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 09:02:53,678] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 09:02:53,683] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 09:02:53,691] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 09:02:53,927] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-02 06:00:00+00:00
[2024-03-30 09:02:54,043] {standard_task_runner.py:52} INFO - Started process 18432 to run task
[2024-03-30 09:02:54,256] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2022-12-02T06:00:00+00:00', '--job-id', '2584', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp_6f1s0o0', '--error-file', '/tmp/tmpmeco9h8q']
[2024-03-30 09:02:54,449] {standard_task_runner.py:77} INFO - Job 2584: Subtask local_to_gcs_task
[2024-03-30 09:02:56,321] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 09:02:59,198] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 09:02:59,532] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T06:00:00+00:00
[2024-03-30 09:03:02,439] {logging_mixin.py:109} INFO - File /opt/***/yellowtaxi_tripdata_2022-12.parquet uploaded to yellowtaxi_tripdata/yellow_taxi_2022_12.parquet.
[2024-03-30 09:03:02,448] {python.py:175} INFO - Done. Returned value was: None
[2024-03-30 09:03:02,522] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20221202T060000, start_date=20240330T090253, end_date=20240330T090302
[2024-03-30 09:03:02,652] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-30 09:03:03,050] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-30 11:57:25,536] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 11:57:25,599] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-03-30 11:57:25,599] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 11:57:25,599] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-30 11:57:25,599] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-30 11:57:25,656] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-02 06:00:00+00:00
[2024-03-30 11:57:25,673] {standard_task_runner.py:52} INFO - Started process 28588 to run task
[2024-03-30 11:57:25,717] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2022-12-02T06:00:00+00:00', '--job-id', '2903', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpdhvtnj8g', '--error-file', '/tmp/tmpsgd9g0fs']
[2024-03-30 11:57:25,727] {standard_task_runner.py:77} INFO - Job 2903: Subtask local_to_gcs_task
[2024-03-30 11:57:25,864] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [running]> on host 98c5b3fde4c4
[2024-03-30 11:57:25,947] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-30 11:57:26,003] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T06:00:00+00:00
[2024-03-30 11:57:31,232] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 68, in upload_to_gcs
    df.to_parquet(clean_file_name, index=False)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2372, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 276, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 101, in write
    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
  File "pyarrow/table.pxi", line 1561, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 607, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 581, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 575, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 302, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column store_and_fwd_flag with type object')
[2024-03-30 11:57:31,290] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20221202T060000, start_date=20240330T115725, end_date=20240330T115731
[2024-03-30 11:57:31,352] {standard_task_runner.py:92} ERROR - Failed to execute job 2903 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 68, in upload_to_gcs
    df.to_parquet(clean_file_name, index=False)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2372, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 276, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parquet.py", line 101, in write
    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
  File "pyarrow/table.pxi", line 1561, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 607, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 581, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.6/site-packages/pyarrow/pandas_compat.py", line 575, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 302, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column store_and_fwd_flag with type object')
[2024-03-30 11:57:31,512] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-30 11:57:31,633] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30 03:02:05,686] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-04-30 03:02:05,734] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-04-30 03:02:05,734] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 03:02:05,735] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-04-30 03:02:05,735] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 03:02:05,985] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-02 06:00:00+00:00
[2024-04-30 03:02:06,014] {standard_task_runner.py:52} INFO - Started process 952 to run task
[2024-04-30 03:02:06,051] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2022-12-02T06:00:00+00:00', '--job-id', '3194', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpw3zsb4y7', '--error-file', '/tmp/tmpj4thx544']
[2024-04-30 03:02:06,145] {standard_task_runner.py:77} INFO - Job 3194: Subtask local_to_gcs_task
[2024-04-30 03:02:07,039] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [running]> on host 02dc49e0e362
[2024-04-30 03:02:07,568] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-30 03:02:07,815] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T06:00:00+00:00
[2024-04-30 03:02:09,599] {python.py:175} INFO - Done. Returned value was: None
[2024-04-30 03:02:09,894] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20221202T060000, start_date=20240430T030205, end_date=20240430T030209
[2024-04-30 03:02:09,992] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-04-30 03:02:10,158] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-30 04:34:14,820] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-04-30 04:34:14,841] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [queued]>
[2024-04-30 04:34:14,842] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 04:34:14,842] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-04-30 04:34:14,842] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 04:34:14,862] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-12-02 06:00:00+00:00
[2024-04-30 04:34:14,892] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery', 'local_to_gcs_task', 'scheduled__2022-12-02T06:00:00+00:00', '--job-id', '3291', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpe44nhxdf', '--error-file', '/tmp/tmpd_nso2bp']
[2024-04-30 04:34:14,902] {standard_task_runner.py:77} INFO - Job 3291: Subtask local_to_gcs_task
[2024-04-30 04:34:14,884] {standard_task_runner.py:52} INFO - Started process 5614 to run task
[2024-04-30 04:34:15,038] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery.local_to_gcs_task scheduled__2022-12-02T06:00:00+00:00 [running]> on host 02dc49e0e362
[2024-04-30 04:34:15,121] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-04-30 04:34:15,185] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-02T06:00:00+00:00
[2024-04-30 04:34:28,254] {python.py:175} INFO - Done. Returned value was: None
[2024-04-30 04:34:28,283] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery, task_id=local_to_gcs_task, execution_date=20221202T060000, start_date=20240430T043414, end_date=20240430T043428
[2024-04-30 04:34:28,346] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-04-30 04:34:28,404] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
