[2024-03-26 15:16:21,059] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-26 15:16:21,215] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-26 15:16:21,215] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 15:16:21,215] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 15:16:21,215] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 15:16:21,338] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-04-02 06:00:00+00:00
[2024-03-26 15:16:21,419] {standard_task_runner.py:52} INFO - Started process 147 to run task
[2024-03-26 15:16:21,456] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp1fr3bwkn', '--error-file', '/tmp/tmpvqplp14o']
[2024-03-26 15:16:21,460] {standard_task_runner.py:77} INFO - Job 225: Subtask download_dataset_task
[2024-03-26 15:16:21,812] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [running]> on host 153a478eba08
[2024-03-26 15:16:22,080] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 15:16:22,196] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2024-03-26 15:16:22,198] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 15:16:22,201] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL <***.models.param.DagParam object at 0x7f7764fe9ac8> > /opt/***/raw_data/yellowtaxi _tripdata_2021-04.csv']
[2024-03-26 15:16:22,353] {subprocess.py:85} INFO - Output:
[2024-03-26 15:16:22,388] {subprocess.py:89} INFO - bash: -c: line 0: syntax error near unexpected token `>'
[2024-03-26 15:16:22,390] {subprocess.py:89} INFO - bash: -c: line 0: `curl -sSL <***.models.param.DagParam object at 0x7f7764fe9ac8> > /opt/***/raw_data/yellowtaxi _tripdata_2021-04.csv'
[2024-03-26 15:16:22,402] {subprocess.py:93} INFO - Command exited with return code 1
[2024-03-26 15:16:22,499] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-26 15:16:22,596] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20210402T060000, start_date=20240326T151621, end_date=20240326T151622
[2024-03-26 15:16:22,700] {standard_task_runner.py:92} ERROR - Failed to execute job 225 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-26 15:16:22,762] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 15:16:23,000] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:33:31,754] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-26 17:33:31,796] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-26 17:33:31,796] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:33:31,796] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:33:31,796] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:33:31,830] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-04-02 06:00:00+00:00
[2024-03-26 17:33:31,855] {standard_task_runner.py:52} INFO - Started process 2735 to run task
[2024-03-26 17:33:31,869] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpsw0ic3h5', '--error-file', '/tmp/tmpjm3rhd75']
[2024-03-26 17:33:31,870] {standard_task_runner.py:77} INFO - Job 385: Subtask download_dataset_task
[2024-03-26 17:33:32,027] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [running]> on host d71984e59113
[2024-03-26 17:33:32,137] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:33:32,191] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2024-03-26 17:33:32,193] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:33:32,194] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-04.parquet > /opt/***/yellowtaxi_tripdata_2021-04.parquet']
[2024-03-26 17:33:32,259] {subprocess.py:85} INFO - Output:
[2024-03-26 17:33:37,316] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:33:37,487] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20210402T060000, start_date=20240326T173331, end_date=20240326T173337
[2024-03-26 17:33:37,629] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:33:37,775] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:48:18,847] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-26 17:48:18,887] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-26 17:48:18,887] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:48:18,887] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:48:18,887] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:48:18,925] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-04-02 06:00:00+00:00
[2024-03-26 17:48:18,933] {standard_task_runner.py:52} INFO - Started process 143 to run task
[2024-03-26 17:48:18,961] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '464', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpvzid8lve', '--error-file', '/tmp/tmp47kttj8a']
[2024-03-26 17:48:18,962] {standard_task_runner.py:77} INFO - Job 464: Subtask download_dataset_task
[2024-03-26 17:48:19,205] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:48:19,386] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:48:19,475] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2024-03-26 17:48:19,477] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:48:19,478] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-04.parquet > /opt/***/yellowtaxi_tripdata_2021-04.parquet']
[2024-03-26 17:48:19,546] {subprocess.py:85} INFO - Output:
[2024-03-26 17:48:24,659] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:48:24,784] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20210402T060000, start_date=20240326T174818, end_date=20240326T174824
[2024-03-26 17:48:24,902] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:48:25,025] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:51:53,975] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-26 17:51:54,017] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-26 17:51:54,017] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:51:54,017] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:51:54,017] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:51:54,095] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-04-02 06:00:00+00:00
[2024-03-26 17:51:54,132] {standard_task_runner.py:52} INFO - Started process 570 to run task
[2024-03-26 17:51:54,150] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '542', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpf3j534hh', '--error-file', '/tmp/tmpmlvssmxi']
[2024-03-26 17:51:54,155] {standard_task_runner.py:77} INFO - Job 542: Subtask download_dataset_task
[2024-03-26 17:51:54,427] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:51:54,560] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:51:54,636] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2024-03-26 17:51:54,638] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:51:54,638] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-04.parquet > /opt/***/yellowtaxi_tripdata_2021-04.parquet']
[2024-03-26 17:51:54,684] {subprocess.py:85} INFO - Output:
[2024-03-26 17:51:59,704] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:52:00,063] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20210402T060000, start_date=20240326T175153, end_date=20240326T175200
[2024-03-26 17:52:00,237] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:52:00,351] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-26 18:02:36,438] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-26 18:02:36,524] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-26 18:02:36,524] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:02:36,524] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 18:02:36,525] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:02:36,565] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-04-02 06:00:00+00:00
[2024-03-26 18:02:36,591] {standard_task_runner.py:52} INFO - Started process 1309 to run task
[2024-03-26 18:02:36,629] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '621', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmplc3sr5mi', '--error-file', '/tmp/tmpglvvaq4c']
[2024-03-26 18:02:36,630] {standard_task_runner.py:77} INFO - Job 621: Subtask download_dataset_task
[2024-03-26 18:02:36,767] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 18:02:36,859] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 18:02:36,927] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2024-03-26 18:02:36,928] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 18:02:36,929] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-04.parquet > /opt/***/yellowtaxi_tripdata_2021-04.parquet']
[2024-03-26 18:02:36,985] {subprocess.py:85} INFO - Output:
[2024-03-26 18:02:41,843] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 18:02:41,918] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20210402T060000, start_date=20240326T180236, end_date=20240326T180241
[2024-03-26 18:02:41,967] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 18:02:42,035] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-27 02:47:46,633] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-27 02:47:46,735] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-27 02:47:46,739] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 02:47:46,748] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-27 02:47:46,748] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 02:47:46,788] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-04-02 06:00:00+00:00
[2024-03-27 02:47:46,812] {standard_task_runner.py:52} INFO - Started process 1317 to run task
[2024-03-27 02:47:46,846] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '725', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpw22j9w9g', '--error-file', '/tmp/tmpdead4jbm']
[2024-03-27 02:47:46,847] {standard_task_runner.py:77} INFO - Job 725: Subtask download_dataset_task
[2024-03-27 02:47:47,115] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-27 02:47:47,204] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-27 02:47:47,249] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2024-03-27 02:47:47,261] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-27 02:47:47,262] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-04.parquet > /opt/***/yellowtaxi_tripdata_2021-04.parquet']
[2024-03-27 02:47:47,298] {subprocess.py:85} INFO - Output:
[2024-03-27 02:47:52,267] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-27 02:47:52,568] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20210402T060000, start_date=20240327T024746, end_date=20240327T024752
[2024-03-27 02:47:52,760] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-27 02:47:53,057] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-28 01:58:30,408] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-28 01:58:30,451] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [queued]>
[2024-03-28 01:58:30,451] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 01:58:30,451] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 01:58:30,451] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 01:58:30,518] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-04-02 06:00:00+00:00
[2024-03-28 01:58:30,539] {standard_task_runner.py:52} INFO - Started process 679 to run task
[2024-03-28 01:58:30,543] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2021-04-02T06:00:00+00:00', '--job-id', '804', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp52ecvypi', '--error-file', '/tmp/tmpr7t3b5zl']
[2024-03-28 01:58:30,544] {standard_task_runner.py:77} INFO - Job 804: Subtask download_dataset_task
[2024-03-28 01:58:30,663] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2021-04-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 01:58:30,775] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 01:58:30,826] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-02T06:00:00+00:00
[2024-03-28 01:58:30,828] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-28 01:58:30,828] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-04.parquet > /opt/***/yellowtaxi_tripdata_2021-04.parquet']
[2024-03-28 01:58:30,855] {subprocess.py:85} INFO - Output:
[2024-03-28 01:58:36,180] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-28 01:58:36,304] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20210402T060000, start_date=20240328T015830, end_date=20240328T015836
[2024-03-28 01:58:36,454] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-28 01:58:36,641] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
