[2024-03-26 15:16:29,130] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-26 15:16:29,171] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-26 15:16:29,171] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 15:16:29,171] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 15:16:29,171] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 15:16:29,205] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-03-02 06:00:00+00:00
[2024-03-26 15:16:29,212] {standard_task_runner.py:52} INFO - Started process 191 to run task
[2024-03-26 15:16:29,235] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpidzth4zi', '--error-file', '/tmp/tmpnhqo2sts']
[2024-03-26 15:16:29,235] {standard_task_runner.py:77} INFO - Job 237: Subtask download_dataset_task
[2024-03-26 15:16:29,377] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [running]> on host 153a478eba08
[2024-03-26 15:16:29,472] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 15:16:29,538] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2024-03-26 15:16:29,540] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 15:16:29,541] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL <***.models.param.DagParam object at 0x7f776547cf98> > /opt/***/raw_data/yellowtaxi _tripdata_2022-03.csv']
[2024-03-26 15:16:29,579] {subprocess.py:85} INFO - Output:
[2024-03-26 15:16:29,596] {subprocess.py:89} INFO - bash: -c: line 0: syntax error near unexpected token `>'
[2024-03-26 15:16:29,596] {subprocess.py:89} INFO - bash: -c: line 0: `curl -sSL <***.models.param.DagParam object at 0x7f776547cf98> > /opt/***/raw_data/yellowtaxi _tripdata_2022-03.csv'
[2024-03-26 15:16:29,597] {subprocess.py:93} INFO - Command exited with return code 1
[2024-03-26 15:16:29,747] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-26 15:16:29,765] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220302T060000, start_date=20240326T151629, end_date=20240326T151629
[2024-03-26 15:16:29,842] {standard_task_runner.py:92} ERROR - Failed to execute job 237 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-26 15:16:29,900] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 15:16:30,113] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:33:40,874] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-26 17:33:41,012] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-26 17:33:41,012] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:33:41,012] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:33:41,012] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:33:41,123] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-03-02 06:00:00+00:00
[2024-03-26 17:33:41,150] {standard_task_runner.py:52} INFO - Started process 2798 to run task
[2024-03-26 17:33:41,182] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmprhlaktjm', '--error-file', '/tmp/tmpk5cec9et']
[2024-03-26 17:33:41,185] {standard_task_runner.py:77} INFO - Job 397: Subtask download_dataset_task
[2024-03-26 17:33:41,705] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [running]> on host d71984e59113
[2024-03-26 17:33:42,095] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:33:42,196] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2024-03-26 17:33:42,200] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:33:42,205] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet > /opt/***/yellowtaxi_tripdata_2022-03.parquet']
[2024-03-26 17:33:42,314] {subprocess.py:85} INFO - Output:
[2024-03-26 17:33:48,976] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:33:49,045] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220302T060000, start_date=20240326T173340, end_date=20240326T173349
[2024-03-26 17:33:49,126] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:33:49,231] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:48:28,287] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-26 17:48:28,348] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-26 17:48:28,350] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:48:28,350] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:48:28,351] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:48:28,396] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-03-02 06:00:00+00:00
[2024-03-26 17:48:28,427] {standard_task_runner.py:52} INFO - Started process 210 to run task
[2024-03-26 17:48:28,461] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '477', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpxz19i735', '--error-file', '/tmp/tmp03s4d0hk']
[2024-03-26 17:48:28,463] {standard_task_runner.py:77} INFO - Job 477: Subtask download_dataset_task
[2024-03-26 17:48:28,639] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:48:28,791] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:48:28,882] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2024-03-26 17:48:28,884] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:48:28,890] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet > /opt/***/yellowtaxi_tripdata_2022-03.parquet']
[2024-03-26 17:48:29,014] {subprocess.py:85} INFO - Output:
[2024-03-26 17:48:35,730] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:48:35,773] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220302T060000, start_date=20240326T174828, end_date=20240326T174835
[2024-03-26 17:48:35,817] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:48:35,874] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:52:05,450] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-26 17:52:05,625] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-26 17:52:05,625] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:52:05,625] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:52:05,625] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:52:05,765] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-03-02 06:00:00+00:00
[2024-03-26 17:52:05,859] {standard_task_runner.py:52} INFO - Started process 641 to run task
[2024-03-26 17:52:05,972] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '556', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpne4cumy8', '--error-file', '/tmp/tmpja7fphqe']
[2024-03-26 17:52:05,972] {standard_task_runner.py:77} INFO - Job 556: Subtask download_dataset_task
[2024-03-26 17:52:06,363] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:52:06,638] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:52:06,791] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2024-03-26 17:52:06,795] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:52:06,796] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet > /opt/***/yellowtaxi_tripdata_2022-03.parquet']
[2024-03-26 17:52:06,869] {subprocess.py:85} INFO - Output:
[2024-03-26 17:52:13,697] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:52:13,734] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220302T060000, start_date=20240326T175205, end_date=20240326T175213
[2024-03-26 17:52:13,758] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:52:13,800] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-26 18:03:15,856] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-26 18:03:15,904] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-26 18:03:15,904] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:03:15,904] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 18:03:15,905] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:03:15,953] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-03-02 06:00:00+00:00
[2024-03-26 18:03:15,972] {standard_task_runner.py:52} INFO - Started process 1473 to run task
[2024-03-26 18:03:16,021] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '640', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpwiiibsqa', '--error-file', '/tmp/tmpmlvox3hz']
[2024-03-26 18:03:16,065] {standard_task_runner.py:77} INFO - Job 640: Subtask download_dataset_task
[2024-03-26 18:03:16,420] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 18:03:16,814] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 18:03:16,964] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2024-03-26 18:03:16,972] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 18:03:16,979] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet > /opt/***/yellowtaxi_tripdata_2022-03.parquet']
[2024-03-26 18:03:17,142] {subprocess.py:85} INFO - Output:
[2024-03-26 18:03:24,258] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 18:03:25,209] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220302T060000, start_date=20240326T180315, end_date=20240326T180325
[2024-03-26 18:03:25,504] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 18:03:25,987] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-27 02:47:58,384] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-27 02:47:58,729] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-27 02:47:58,730] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 02:47:58,730] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-27 02:47:58,730] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 02:47:58,993] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-03-02 06:00:00+00:00
[2024-03-27 02:47:59,148] {standard_task_runner.py:52} INFO - Started process 1399 to run task
[2024-03-27 02:47:59,188] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '738', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpmxcl_gr8', '--error-file', '/tmp/tmp49gtdr4o']
[2024-03-27 02:47:59,189] {standard_task_runner.py:77} INFO - Job 738: Subtask download_dataset_task
[2024-03-27 02:47:59,568] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-27 02:47:59,837] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-27 02:47:59,952] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2024-03-27 02:47:59,954] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-27 02:47:59,964] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet > /opt/***/yellowtaxi_tripdata_2022-03.parquet']
[2024-03-27 02:48:00,026] {subprocess.py:85} INFO - Output:
[2024-03-27 02:48:07,041] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-27 02:48:07,357] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220302T060000, start_date=20240327T024758, end_date=20240327T024807
[2024-03-27 02:48:07,531] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-27 02:48:07,779] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-28 01:58:39,181] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-28 01:58:39,270] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [queued]>
[2024-03-28 01:58:39,271] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 01:58:39,274] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 01:58:39,274] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 01:58:39,423] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-03-02 06:00:00+00:00
[2024-03-28 01:58:39,434] {standard_task_runner.py:52} INFO - Started process 759 to run task
[2024-03-28 01:58:39,451] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-03-02T06:00:00+00:00', '--job-id', '816', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpjhdejtt3', '--error-file', '/tmp/tmpr0q1_u53']
[2024-03-28 01:58:39,452] {standard_task_runner.py:77} INFO - Job 816: Subtask download_dataset_task
[2024-03-28 01:58:39,741] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-03-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 01:58:39,891] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 01:58:40,001] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T06:00:00+00:00
[2024-03-28 01:58:40,009] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-28 01:58:40,011] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet > /opt/***/yellowtaxi_tripdata_2022-03.parquet']
[2024-03-28 01:58:40,094] {subprocess.py:85} INFO - Output:
[2024-03-28 01:58:46,816] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-28 01:58:47,256] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220302T060000, start_date=20240328T015839, end_date=20240328T015847
[2024-03-28 01:58:47,538] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-28 01:58:47,757] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
