[2024-03-26 15:16:31,008] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-26 15:16:31,041] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-26 15:16:31,041] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 15:16:31,041] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 15:16:31,041] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 15:16:31,071] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-26 15:16:31,078] {standard_task_runner.py:52} INFO - Started process 203 to run task
[2024-03-26 15:16:31,091] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp_slmfm5i', '--error-file', '/tmp/tmpnbtpswj4']
[2024-03-26 15:16:31,103] {standard_task_runner.py:77} INFO - Job 241: Subtask download_dataset_task
[2024-03-26 15:16:31,219] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host 153a478eba08
[2024-03-26 15:16:31,283] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 15:16:31,319] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-26 15:16:31,320] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 15:16:31,321] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL <***.models.param.DagParam object at 0x7f7765472518> > /opt/***/raw_data/yellowtaxi _tripdata_2022-07.csv']
[2024-03-26 15:16:31,337] {subprocess.py:85} INFO - Output:
[2024-03-26 15:16:31,341] {subprocess.py:89} INFO - bash: -c: line 0: syntax error near unexpected token `>'
[2024-03-26 15:16:31,342] {subprocess.py:89} INFO - bash: -c: line 0: `curl -sSL <***.models.param.DagParam object at 0x7f7765472518> > /opt/***/raw_data/yellowtaxi _tripdata_2022-07.csv'
[2024-03-26 15:16:31,342] {subprocess.py:93} INFO - Command exited with return code 1
[2024-03-26 15:16:31,363] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-26 15:16:31,373] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220702T060000, start_date=20240326T151631, end_date=20240326T151631
[2024-03-26 15:16:31,398] {standard_task_runner.py:92} ERROR - Failed to execute job 241 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-26 15:16:31,429] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 15:16:31,493] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:33:55,970] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-26 17:33:55,993] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-26 17:33:55,994] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:33:55,994] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:33:55,994] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:33:56,020] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-26 17:33:56,032] {standard_task_runner.py:52} INFO - Started process 2858 to run task
[2024-03-26 17:33:56,048] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '416', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpv27yh9j6', '--error-file', '/tmp/tmpsw0yv_ga']
[2024-03-26 17:33:56,049] {standard_task_runner.py:77} INFO - Job 416: Subtask download_dataset_task
[2024-03-26 17:33:56,194] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host d71984e59113
[2024-03-26 17:33:56,257] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:33:56,289] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-26 17:33:56,291] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:33:56,292] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet > /opt/***/yellowtaxi_tripdata_2022-07.parquet']
[2024-03-26 17:33:56,313] {subprocess.py:85} INFO - Output:
[2024-03-26 17:34:02,297] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:34:02,408] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220702T060000, start_date=20240326T173355, end_date=20240326T173402
[2024-03-26 17:34:02,521] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:34:02,576] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:48:48,882] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-26 17:48:48,983] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-26 17:48:48,983] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:48:48,983] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:48:48,983] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:48:49,071] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-26 17:48:49,084] {standard_task_runner.py:52} INFO - Started process 276 to run task
[2024-03-26 17:48:49,109] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '497', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpajxzewt_', '--error-file', '/tmp/tmp_2uqmiv5']
[2024-03-26 17:48:49,109] {standard_task_runner.py:77} INFO - Job 497: Subtask download_dataset_task
[2024-03-26 17:48:49,301] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:48:49,413] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:48:49,462] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-26 17:48:49,464] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:48:49,464] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet > /opt/***/yellowtaxi_tripdata_2022-07.parquet']
[2024-03-26 17:48:49,536] {subprocess.py:85} INFO - Output:
[2024-03-26 17:48:55,755] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:48:56,618] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220702T060000, start_date=20240326T174848, end_date=20240326T174856
[2024-03-26 17:48:56,850] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:48:57,101] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-26 17:52:20,619] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-26 17:52:20,645] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-26 17:52:20,645] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:52:20,646] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 17:52:20,646] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 17:52:20,696] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-26 17:52:20,731] {standard_task_runner.py:52} INFO - Started process 686 to run task
[2024-03-26 17:52:20,743] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '573', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmph_l9h2eg', '--error-file', '/tmp/tmp3oy5wtwn']
[2024-03-26 17:52:20,744] {standard_task_runner.py:77} INFO - Job 573: Subtask download_dataset_task
[2024-03-26 17:52:20,864] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 17:52:20,940] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 17:52:20,996] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-26 17:52:20,997] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 17:52:20,998] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet > /opt/***/yellowtaxi_tripdata_2022-07.parquet']
[2024-03-26 17:52:21,037] {subprocess.py:85} INFO - Output:
[2024-03-26 17:52:27,412] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-26 17:52:27,598] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220702T060000, start_date=20240326T175220, end_date=20240326T175227
[2024-03-26 17:52:27,828] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 17:52:28,552] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 18:04:56,642] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-26 18:04:56,789] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-26 18:04:56,789] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:04:56,789] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 18:04:56,794] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 18:04:56,933] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-26 18:04:57,013] {standard_task_runner.py:52} INFO - Started process 1634 to run task
[2024-03-26 18:04:57,047] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '651', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmpm0fvyp6m', '--error-file', '/tmp/tmpidyqbgiv']
[2024-03-26 18:04:57,084] {standard_task_runner.py:77} INFO - Job 651: Subtask download_dataset_task
[2024-03-26 18:04:57,474] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-26 18:04:57,921] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 18:04:58,297] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-26 18:04:58,298] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-26 18:04:58,299] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet > /opt/***/yellowtaxi_tripdata_2022-07.parquet']
[2024-03-26 18:04:58,649] {subprocess.py:85} INFO - Output:
[2024-03-27 03:48:04,635] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-27 03:48:04,677] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-27 03:48:04,677] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 03:48:04,677] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-27 03:48:04,677] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 03:48:04,705] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-27 03:48:04,720] {standard_task_runner.py:52} INFO - Started process 100 to run task
[2024-03-27 03:48:04,728] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '758', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp67_wn1nx', '--error-file', '/tmp/tmpl8l3kzjm']
[2024-03-27 03:48:04,728] {standard_task_runner.py:77} INFO - Job 758: Subtask download_dataset_task
[2024-03-27 03:48:04,857] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-27 03:48:04,928] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-27 03:48:04,987] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-27 03:48:04,990] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-27 03:48:04,991] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet > /opt/***/yellowtaxi_tripdata_2022-07.parquet']
[2024-03-27 03:48:05,017] {subprocess.py:85} INFO - Output:
[2024-03-27 03:48:11,143] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-27 03:48:11,192] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220702T060000, start_date=20240327T034804, end_date=20240327T034811
[2024-03-27 03:48:11,244] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-27 03:48:11,567] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-28 03:50:09,245] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-28 03:50:09,487] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-28 03:50:09,489] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 03:50:09,490] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 03:50:09,490] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 03:50:09,629] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-28 03:50:09,730] {standard_task_runner.py:52} INFO - Started process 110 to run task
[2024-03-28 03:50:09,855] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '845', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp0ul1p_99', '--error-file', '/tmp/tmptrt4ypkp']
[2024-03-28 03:50:09,878] {standard_task_runner.py:77} INFO - Job 845: Subtask download_dataset_task
[2024-03-28 03:50:11,138] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 03:50:11,261] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 03:50:11,307] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-28 03:50:11,308] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-28 03:50:11,309] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet > /opt/***/yellowtaxi_tripdata_2022-07.parquet']
[2024-03-28 03:50:11,356] {subprocess.py:85} INFO - Output:
[2024-03-28 03:50:20,018] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-28 03:50:20,443] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220702T060000, start_date=20240328T035009, end_date=20240328T035020
[2024-03-28 03:50:20,707] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-28 03:50:20,942] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-28 04:33:36,136] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-28 04:33:36,181] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-28 04:33:36,182] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 04:33:36,183] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 04:33:36,183] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 04:33:36,205] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-28 04:33:36,226] {standard_task_runner.py:52} INFO - Started process 2446 to run task
[2024-03-28 04:33:36,237] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '899', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp4nsclcki', '--error-file', '/tmp/tmpmxplfsu8']
[2024-03-28 04:33:36,238] {standard_task_runner.py:77} INFO - Job 899: Subtask download_dataset_task
[2024-03-28 04:33:36,385] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 04:33:36,462] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 04:33:36,500] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-28 04:33:36,506] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-28 04:33:36,507] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet > /opt/***/yellowtaxi_tripdata_2022-07.parquet']
[2024-03-28 04:33:36,544] {subprocess.py:85} INFO - Output:
[2024-03-28 04:33:41,655] {local_task_job.py:212} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-03-28 04:33:41,729] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 2446. PIDs of all processes in the group: [2447, 2450, 2446]
[2024-03-28 04:33:41,734] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 2446
[2024-03-28 04:33:41,735] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-28 04:33:41,735] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2024-03-28 04:33:41,759] {process_utils.py:70} INFO - Process psutil.Process(pid=2450, status='terminated', started='04:33:36') (2450) terminated with exit code None
[2024-03-28 04:33:41,797] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 182, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-28 04:33:41,828] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220702T060000, start_date=20240328T043336, end_date=20240328T043341
[2024-03-28 04:33:42,008] {standard_task_runner.py:92} ERROR - Failed to execute job 899 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 182, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-28 04:33:42,126] {process_utils.py:70} INFO - Process psutil.Process(pid=2446, status='terminated', exitcode=1, started='04:33:35') (2446) terminated with exit code 1
[2024-03-28 04:33:42,126] {process_utils.py:70} INFO - Process psutil.Process(pid=2447, status='terminated', started='04:33:36') (2447) terminated with exit code None
[2024-03-28 09:17:24,041] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-28 09:17:24,131] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-28 09:17:24,131] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 09:17:24,131] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 09:17:24,131] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 09:17:24,211] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-28 09:17:24,324] {standard_task_runner.py:52} INFO - Started process 88 to run task
[2024-03-28 09:17:24,402] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '982', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp84dj62zg', '--error-file', '/tmp/tmpnq7rmc_1']
[2024-03-28 09:17:24,417] {standard_task_runner.py:77} INFO - Job 982: Subtask download_dataset_task
[2024-03-28 09:17:24,737] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 09:17:25,018] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 09:17:25,116] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-28 09:17:25,118] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-28 09:17:25,118] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet > /opt/***/yellowtaxi_tripdata_2022-07.parquet']
[2024-03-28 09:17:25,144] {subprocess.py:85} INFO - Output:
[2024-03-28 09:17:32,145] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-28 09:17:32,560] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220702T060000, start_date=20240328T091724, end_date=20240328T091732
[2024-03-28 09:17:32,697] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-28 09:17:32,845] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-28 09:47:07,861] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-28 09:47:07,884] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-28 09:47:07,885] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 09:47:07,885] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 09:47:07,886] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 09:47:07,910] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-28 09:47:07,919] {standard_task_runner.py:52} INFO - Started process 1798 to run task
[2024-03-28 09:47:07,933] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '1057', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp0hrpcxqm', '--error-file', '/tmp/tmphfxkfe5o']
[2024-03-28 09:47:07,934] {standard_task_runner.py:77} INFO - Job 1057: Subtask download_dataset_task
[2024-03-28 09:47:08,012] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 09:47:08,061] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 09:47:08,092] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-28 09:47:08,094] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-28 09:47:08,096] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet > /opt/***/yellowtaxi_tripdata_2022-07.parquet']
[2024-03-28 09:47:08,109] {subprocess.py:85} INFO - Output:
[2024-03-28 09:47:15,003] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-28 09:47:15,052] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220702T060000, start_date=20240328T094707, end_date=20240328T094715
[2024-03-28 09:47:15,107] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-28 09:47:15,345] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-28 14:48:29,078] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-28 14:48:29,117] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [queued]>
[2024-03-28 14:48:29,118] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 14:48:29,118] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-28 14:48:29,118] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-28 14:48:29,152] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-07-02 06:00:00+00:00
[2024-03-28 14:48:29,161] {standard_task_runner.py:52} INFO - Started process 109 to run task
[2024-03-28 14:48:29,184] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'download_dataset_task', 'scheduled__2022-07-02T06:00:00+00:00', '--job-id', '1146', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag.py', '--cfg-path', '/tmp/tmp03l4vt57', '--error-file', '/tmp/tmplfbs0es_']
[2024-03-28 14:48:29,185] {standard_task_runner.py:77} INFO - Job 1146: Subtask download_dataset_task
[2024-03-28 14:48:29,372] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.download_dataset_task scheduled__2022-07-02T06:00:00+00:00 [running]> on host 05f84def3a12
[2024-03-28 14:48:29,538] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-28 14:48:29,599] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T06:00:00+00:00
[2024-03-28 14:48:29,601] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-28 14:48:29,601] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-07.parquet > /opt/***/yellowtaxi_tripdata_2022-07.parquet']
[2024-03-28 14:48:29,684] {subprocess.py:85} INFO - Output:
[2024-03-28 14:48:35,722] {subprocess.py:93} INFO - Command exited with return code 0
[2024-03-28 14:48:35,934] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data, task_id=download_dataset_task, execution_date=20220702T060000, start_date=20240328T144829, end_date=20240328T144835
[2024-03-28 14:48:35,976] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-28 14:48:36,054] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
